### ISSUE TITLE
.DS_Store files uploaded

### ISSUE THREAD

**Issue by dtaylorstub** [k1LoW/serverless-s3-sync#110]
My config inside serverless.yml
```
  s3Sync:
    - bucketNameKey: BucketKey
      bucketPrefix: myFolder/
      localDir: myFolder
```

End up with each folder having .DS_Store files
