### ISSUE TITLE
Files removed from S3 even with noSync: true 

### ISSUE THREAD

**Issue by ErikAGriffin** [k1LoW/serverless-s3-sync#116]
Hi, in my `serverless.yml` file I've included the following:

```yml
plugins:
  - serverless-s3-sync
custom:
  s3Sync:
    buckets:
    - bucketName: my-bucket
      bucketPrefix: folder/
      localDir: config/folder
      deleteRemoved: false
      noSync: true # Prevent removal of objects with `sls remove`
```

However, when I run `sls remove -s stage`, the objects are still getting removed from the bucket.
