### ISSUE TITLE
Sync is just one-way?

### ISSUE THREAD

**Issue by ErikAGriffin** [k1LoW/serverless-s3-sync#117]
Perhaps I'm not understanding this library correctly:

- I have configuration files hosted in S3
- I would like `sls s3sync`, or `sls deploy` to sync these files to the specified local folder
- Neither of these commands seem to be downloading the files
- Running `sls remove` does delete the contents of the bucket I have specified

Is syncing from an S3 bucket to the local repository not supported by this library?  Or have I misconfigured something?

Here is what my configuration looks like:

```yml
plugins:
  - serverless-s3-sync
custom:
  s3Sync:
    noSync: false
    buckets:
    - bucketName: my-s3-bucket
      bucketPrefix: config/
      localDir: config/secrets
      deleteRemoved: false
```

Running `sls s3sync` returns the following:
```bash
Running "serverless" from node_modules
(node:15707) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
✔ Synced files to S3 buckets
✔ Synced bucket metadata
✔ Updated bucket tags
```

But nothing is updated in my local folder.  I would like to have the contents of the S3 buckets synced to the serverless package before each deploy, is what I'm trying to achieve.
