### ISSUE TITLE
http header / UnexpectedParameter: Unexpected key 'Service-Worker-Allowed' found in params

### ISSUE THREAD

**Issue by aheissenberger** [k1LoW/serverless-s3-sync#119]
How can I add additional http headers?

Here is my current setup:
```yaml
custom:
  s3Sync:
    - bucketNameKey: WebSiteBucket
      localDir: dist/client
      deleteRemoved: true
      acl: public-read # required
      params:
        - "assets/pwa/sw.js":
            CacheControl: 'no-cache'
            ServiceWorkerAllowed: '/'
        - "assets/pwa/manifest.webmanifest":
            CacheControl: 'no-cache'
        - "*.*":
            CacheControl: 'public, max-age=31536000'
```
