### ISSUE TITLE
add support of Fn::ImportValue

### ISSUE THREAD

**Issue by jefftham** [k1LoW/serverless-s3-sync#19]
i proposed to add support of cloudformation Fn::ImportValue.

eg. 
``` 
s3Sync:
    - bucketName: 
         Fn::ImportValue: otherStackS3Bucket
      bucketPrefix: assests/
      localDir: resources/feature/folder
```
