### ISSUE TITLE
Cache-control headers not getting set

### ISSUE THREAD

**Issue by tremby** [k1LoW/serverless-s3-sync#31]
We're using serverless-s3-sync along with gatsby-plugin-s3 to deploy a site to S3 and Cloudfront.

In serverless.yml:

```yaml
custom:
  frontendBucketName: ${file(./.cache/s3.config.json):bucketName, env:AWS_ORIGIN_S3_BUCKET}
  videoBucketName: ${self:service}-video-${self:provider.stage}
  s3Sync:
  - bucketName: ${self:custom.frontendBucketName}
    localDir: public
    acl: public-read
    defaultContentType: text/html
    params: ${file(./.cache/s3.params.json)}
  certificates:
    ...
```

If I look in `.cache/s3.params.json` it all looks as expected: (reformatted)

```json
{
  "**/**.html": {
    "CacheControl": "public, max-age=0, must-revalidate"
  },
  "static/**": {
    "CacheControl": "public, max-age=31536000, immutable"
  },
  "**/**/!(sw).js": {
    "CacheControl": "public, max-age=31536000, immutable"
  },
  "**/**.css": {
    "CacheControl": "public, max-age=31536000, immutable"
  },
  "sw.js": {
    "CacheControl": "public, max-age=0, must-revalidate"
  }
}
```

Yet the files which end up on S3, which certainly match those paths (such as `static/1-52e5afcd825a509c9e73.js`) only have one metadata attached, the Content-Type.

Feels like there's something obvious we must be missing.

Using serverless-s3-sync@1.8.0

**Comment by tremby** [comment]
Discoveries since my previous message:

- Those globs look very suspect. `**.js` isn't valid is it? I thought double-stars were only for directories, not filenames
- It's an object, not an array. The example has an array, and the source code looks like it expects an array.
- Our test with the example params in your readme didn't seem to help, but I've since discovered that metadata doesn't appear to be set when it's an existing file, only for new (and maybe updated) files. Is this a bug?

So for now we cleared out the bucket and ran it again with this manually set in serverless.yml:

```yaml
  s3Sync:
  - bucketName: ${self:custom.frontendBucketName}
    localDir: public
    acl: public-read
    defaultContentType: text/html
    params:
      - '**/*.html':
          CacheControl: 'public, max-age=0, must-revalidate'
      - '**/*.js':
          CacheControl: 'public, max-age=31536000, immutable'
      - '**/*.css':
          CacheControl: 'public, max-age=31536000, immutable'
      - 'static/**':
          CacheControl: 'public, max-age=31536000, immutable'
      - 'icons/**':
          CacheControl: 'public, max-age=31536000, immutable'
```

And it seems OK.
