### ISSUE TITLE
Validation errors when specifying cache-control

### ISSUE THREAD

**Issue by luludan** [k1LoW/serverless-s3-sync#38]
I'm trying to specify cache-control headers with this syntax:

```yml
  s3Sync:
    - bucketName: ${self:custom.s3Bucket} 
      localDir: .dir/sub_dir
      bucketPrefix: _dir/sub_dir 
      params:
        - '**/*.js':
          CacheControl: 'public, max-age=31536000, immutable'
        - '**/*.css':
          CacheControl: 'public, max-age=31536000, immutable'
        - '**/*.woff':
          CacheControl: 'public, max-age=31536000, immutable'
```

But am getting this error when trying to run `sls deploy`

```
S3 Sync: Syncing directories and S3 prefixes...
.... 
  Multiple Validation Errors -----------------------------
 
  MultipleValidationErrors: There were 35 validation errors:
  * UnexpectedParameter: Unexpected key '0' found in params
  * UnexpectedParameter: Unexpected key '1' found in params
  * UnexpectedParameter: Unexpected key '2' found in params
  * UnexpectedParameter: Unexpected key '3' found in params
  * UnexpectedParameter: Unexpected key '4' found in params
.
.
.
```

Not sure quite what I'm doing wrong here
