### ISSUE TITLE
Bucket not found

### ISSUE THREAD

**Issue by PraveenAsh** [k1LoW/serverless-s3-sync#48]
In the latest version,
The bucket name isnt being read unless globally installed. When rolled back to v1.7.2 works just fine.

It directly throws error msg stating,
```bash
S3 Sync: Synced metadata.
No Such Bucket -----------------------------------------
```

Please keep the backward support on.
@k1LoW @nibynool

**Comment by k1LoW** [comment]
Hi @PraveenAsh .

- Could you show me serverless.yml (`s3Sync:` ) ?
- What is the latest version that works in your environment? ( 1.7.2 -> OK, 1.7.3 -> NG? )

**Comment by PraveenAsh** [comment]
serversless.yml :
```yaml
 s3Sync:
    - bucketName: ${self:custom.siteName}
      bucketPrefix: ${self:custom.stage}
      localDir: static
      params: 
        - randomname.html:
            CacheControl: 'no-cache'
```

The custom variables exist but don't get picked. But the credentials exist in the environment with aws prefix.

The latest that failed was `v1.10.2` but works fine in `v1.7.2`
OS : Catalina, MacOS
