### ISSUE TITLE
double sync

### ISSUE THREAD

**Issue by lsanders** [k1LoW/serverless-s3-sync#57]
I have just a single budket/prefix defined, but end up the the files from build in both the root AND the bucketPrefix and have the following log in serverless deploy

```
S3 Sync: Syncing directories and S3 prefixes...
........
S3 Sync: Synced.
S3 Sync: Syncing metadata...
.
S3 Sync: Synced metadata.
```

Here's the relevant config:
```
  s3Sync:
    - bucketName: ${self:custom.siteName}
      bucketPrefix: shell/
      localDir: build
      params:
        - 'index.html':
            CacheControl: 'max-age=0,no-cache,no-store,must-revalidate'
        - 'sw.js':
            CacheControl: 'max-age=0,no-cache,no-store,must-revalidate'
```

This deployed via bitbucket pipelines but I don't think that matters.
