### ISSUE TITLE
Using Ref as bucketName

### ISSUE THREAD

**Issue by iDVB** [k1LoW/serverless-s3-sync#6]
It seems like whenever we use something like `{Ref: WebSite}` for the bucketname we get an error like....

`Expected params.Bucket to be a string`

**Comment by k1LoW** [comment]
Hi @iDVB .
Because, `custom.s3Sync.bucketName` is **NOT** `resources` section.

Best regards.

**Comment by iDVB** [comment]
@k1LoW indeed. However, it is the custom variable variable section where it is also valid to use CloudFormation `Ref`s. Which works with plain vars and with many other plugins.... just not this one. 

As mentioned in the [docs](https://serverless.com/framework/docs/providers/aws/guide/plugins/)...
>Note: Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.

So if you wanted to support this, you could, you just need to wait for later hook.  In the mean time, for those looking for this feature now. You can use cf notation and grab it from the cf outputs.
```
  s3Sync:
    - bucketName: ${cf:${self:custom.stackname}.Website}
      localDir: static
```

Works for me.

**Comment by tommedema** [comment]
@iDVB your request is totally valid, but it is not a good idea to use `${cf:}`. Reason is that this won't work if your s3 bucket has not yet been created.

Following basic infrastructure as code principles, it should not be important whether the resource you are referencing to has been created or not. If it is not, it should be created automatically. Unfortunately this is not how `${cf}` works, but `Ref:` does work as such. Therefore the original request for Ref to work seems very useful.

**Comment by iDVB** [comment]
@tommedema Thanks. 
Yes, ${cf} is just a bandaid until we can either patch or fork `serverless-s3-sync`.

@k1LoW would you accept a PR if we add this feature?

**Comment by k1LoW** [comment]
@iDVB 
> would you accept a PR if we add this feature?
YES!!! I’m so excited about PR!!!

**Comment by mpvosseller** [comment]
I'd love to use this plugin without having to know the S3 bucket name as well. A possible implementation could be to have the user Output the bucket name and provide the key to the plugin so it can read it. `serverless.yml` might look something like this:

```
custom:
    s3Sync:
        - bucketNameOutputKey: MyS3BucketNameKey    
           localDir: dist

resources:
    Resources:
        MyS3Bucket:
            Type: AWS::S3::Bucket

    Outputs:
        MyS3BucketNameKey:
            Value:
                Ref: MyS3Bucket 
```

The [serverless-cloudfront-invalidate plugin](https://github.com/aghadiry/serverless-cloudfront-invalidate) does something nearly identical but for a CloudFront Distribution Id.
