### ISSUE TITLE
Support S3 bucket tag updates

### ISSUE THREAD

**Issue by coyoteecd** [k1LoW/serverless-s3-sync#60]
Use case:

- main repo deploys CloudFormation stack, which includes S3 bucket necessary for SPA web app
- web app repo uses a minimal serverless.yml with serverless-s3-sync plugin to build the SPA web app and publish the files to the existing S3 bucket created by main repo

I'd like to write/update a tag on the S3 bucket, containing information from the web app repo at the time of copying files. For example, write the git commit SHA and maybe branch name.

Configuration might look like this:
```
s3Sync:
    - bucketName: my-static-site # required
      localDir: dist # required
      bucketTags:
         tagKey1: tagValue1
         tagKey2: tagValue2
```
After sync, the plugin would use `putBucketTagging` to write the tags - see [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketTagging-property). 

Writing tags is not a "tag sync". This means the tags configured are written as-is, therefore:
- an existing tagKey will be overwritten if it exists
- renaming a tagKey will NOT delete the previously written tagKey with the old value
- removing a previously written tagKey from the bucketTags entry will NOT remove it from the bucket (on the next sync)
The reason for this behavior is to make sure tags added by other tools (e.g. Serverless deployment that created the bucket) are left untouched when running s3sync.

@k1LoW Does the above sound good? I can fork and submit a pull request with the implementation.
