### ISSUE TITLE
Files uploaded twice with bucketPrefix

### ISSUE THREAD

**Issue by DimiF4W** [k1LoW/serverless-s3-sync#85]
Hi guys,

Im a new user of s3sync with serverless but I noticed my files are uploaded 2 times if I use bucketPrefix.
My files are always uploaded in the root AND in the bucketPrefix/folder.

```
custom:
  s3Sync:
    - bucketNameKey: AssetBucketRef
      bucketPrefix: assets
      localDir: ./dist/
      deleteRemoved: true
      acl: public-read
      params:
        - "*.*":
            CacheControl: 'public, max-age=31536000'
```

This results in a /assets/xxx.json file AND a /xxx.json file.
If I remove files and deleteRemoved is enabled, only the files in the  bucketPrefix folder are removed, the files in the root are not removed.

Can someone check this please?

Thanks
